* Structure and Interpretation of Computer Programs Notes

This repo contains my personal self study notes from reading the book by
Abelson, Sussman, and the other Sussman. To be more specific the second
edition.

+Currently stuck on chapter 2, skipped my last exercise. Will now focus
on learning computer systems and algorithms.+

I am back from suffering in Algorithms land. By that I mean that I was
procrastinating and doing other unrelated things. I was reading Art of
Computer Programming and I got even more depressed because I could get
fast enough to my true goal of writing my own Minecraft clone.

Crafting Interpreters can be read before or after this book.

** Goals
- [X] Learn a LISP language
- [X] learn to code, hard way
- [X] create a strategy for note-taking
- [X] create strategy for organizing exercises
- [X] configure Neovim for Lisp code editing
- [X] configure Neovim for note-taking.
  - [ ] configure for ORG documents
- [ ] attempt to use other editors for writing code
- [ ] write notes in writing, condense to main ideas in this repo
- [ ] write compiler in GNU Guild
- [ ] finish book
- [ ] move all notes to Notes to ORG documents
- [ ] use doom emacs to take notes and write code
  - [ ] for some reason I can't use the Geiser REPL plugin for stupid reason
