* Structure and Interpretation of Computer Programs Notes

This repo contains my personal self study notes from reading the book by
Abelson, Sussman, and the other Sussman. To be more specific the second
edition.

+Currently stuck on chapter 2, skipped my last exercise. Will now focus
on learning computer systems and algorithms.+

I am back from suffering in Algorithms land. By that I mean that I was
procrastinating and doing other unrelated things. I was reading Art of
Computer Programming and I got even more depressed because I could get
fast enough to my true goal of writing my own Minecraft clone.

Crafting Interpreters can be read before or after this book.

** Goals
- [ ] finish book
- [ ] learn ORG mode
- [X] Learn a LISP language
- [X] learn to code, hard way
- [X] create a strategy for note-taking
- [X] create strategy for organizing exercises
- [X] configure Neovim for Lisp code editing
- [X] configure Neovim for note-taking.
  - [X] configure for ORG documents
- [X] attempt to use other editors for writing code
  - sticking to Emacs with Lisp editing tools and Geiser
- [X] write compiler in GNU Guild
- [ ] move all notes to Notes to ORG documents
- [ ] switch to my own configured version of emacs
- [ ] stick to Emacs for SICP, helix for everything and anything that has a proper language server


** Example of Scheme Code

#+begin_src scheme
(define (square x) (* x x))
(define relu (lambda (x) (if (< x 0)
                             0
                             x))))
(square 3)
(relu 7)
(display "Hello World!\n")
(relu -2)
#+end_src
