(define (f n)
  (cond ((< n 3) n)
        ((>= n 3) (+
                    (f (- n 1))
                    (* 2 (f (- n 2)))
                    (* 3 (f (- n 3)))
                  )
        )
  )
)

(define (g-iter n m f1 f2 f3)
  (define fnew (+ f1 (* 2 f2) (* 3 f3)))
  (cond ((< m n) (g-iter n (+ m 1) fnew f1 f2))
        (else f3)))

(define (g n)
  (cond ((< n 3) n)
        (else (g-iter n 0 2 1 0 ))))

(define (test x)
  (write "Eval f(n) for ")
  (write x)
  (write " is ")
  (write (f x))
  (write " Eval g(n) for ")
  (write x)
  (write " is ")
  (write (g x))
  (newline)
)

(test 0)
(test 1)
(test 2)
(test 3)
(test 4)
(test 5)
(test 6)
(test 7)
(test 8)
(test 9)
